// Mock data for ForgeAxis Dashboard

export const kpiCards = [
  {
    id: "todo",
    title: "Total Customers",
    description: "Active manufacturing partners",
    value: "24",
    change: "+3",
    changeType: "increase" as const,
    color: "cyan" as const,
    icon: "ClipboardList" as const,
  },
  {
    id: "total-orders",
    title: "Total Orders",
    description: "Processing for current month",
    value: "1,847",
    change: "+12.5%",
    changeType: "increase" as const,
    color: "blue" as const,
    icon: "ShoppingCart" as const,
  },
  {
    id: "balance",
    title: "Balance orders",
    description: "Value of unfulfilled orders",
    value: "₹48.2M",
    change: "+8.3%",
    changeType: "increase" as const,
    color: "emerald" as const,
    icon: "Wallet" as const,
  },
  {
    id: "revenue",
    title: "Revenue",
    description: "Total earnings this quarter",
    value: "₹124.7M",
    change: "+22.1%",
    changeType: "increase" as const,
    color: "purple" as const,
    icon: "TrendingUp" as const,
  },
];

export const workflowModules = [
  {
    id: "stock",
    title: "Stock section wise",
    description: "Overall inventory status across all categories",
    value: "8,432",
    unit: "units",
    status: "optimal" as const,
    percentage: 78,
    color: "cyan" as const,
    icon: "Package" as const,
    alerts: 2,
    trend: "+5.2%",
  },
  {
    id: "copper",
    title: "Copper",
    description: "Raw copper material tracking",
    value: "4,820",
    unit: "kg",
    status: "low" as const,
    percentage: 34,
    color: "amber" as const,
    icon: "Zap" as const,
    alerts: 3,
    trend: "-8.1%",
  },
  {
    id: "steel",
    title: "Steel",
    description: "Structural steel inventory",
    value: "4,820",
    unit: "kg",
    status: "low" as const,
    percentage: 34,
    color: "amber" as const,
    icon: "Zap" as const,
    alerts: 3,
    trend: "-8.1%",
  },
  {
    id: "purchase",
    title: "Purchase",
    description: "Vendor procurement and orders",
    value: "₹2.4M",
    unit: "this month",
    status: "active" as const,
    percentage: 62,
    color: "blue" as const,
    icon: "ShoppingBag" as const,
    alerts: 0,
    trend: "+14.2%",
  },
  {
    id: "sales",
    title: "Sales",
    description: "Revenue and customer orders",
    value: "₹8.6M",
    unit: "this month",
    status: "active" as const,
    percentage: 85,
    color: "emerald" as const,
    icon: "BarChart3" as const,
    alerts: 0,
    trend: "+18.5%",
  },
];

export const revenueData = [
  { month: "Jan", revenue: 65, expenses: 42, profit: 23 },
  { month: "Feb", revenue: 78, expenses: 48, profit: 30 },
  { month: "Mar", revenue: 90, expenses: 52, profit: 38 },
  { month: "Apr", revenue: 81, expenses: 45, profit: 36 },
  { month: "May", revenue: 96, expenses: 58, profit: 38 },
  { month: "Jun", revenue: 110, expenses: 61, profit: 49 },
  { month: "Jul", revenue: 124, expenses: 67, profit: 57 },
  { month: "Aug", revenue: 118, expenses: 63, profit: 55 },
  { month: "Sep", revenue: 135, expenses: 72, profit: 63 },
  { month: "Oct", revenue: 148, expenses: 78, profit: 70 },
  { month: "Nov", revenue: 142, expenses: 74, profit: 68 },
  { month: "Dec", revenue: 160, expenses: 82, profit: 78 },
];

export const inventoryData = [
  { category: "Copper Wire", stock: 4820, capacity: 14000, unit: "kg", status: "low" },
  { category: "Steel Sheets", stock: 8200, capacity: 12000, unit: "kg", status: "optimal" },
  { category: "Aluminum Rods", stock: 3600, capacity: 8000, unit: "kg", status: "optimal" },
  { category: "Plastic Casing", stock: 12400, capacity: 15000, unit: "units", status: "high" },
  { category: "Circuit Boards", stock: 1800, capacity: 5000, unit: "units", status: "critical" },
  { category: "Fasteners", stock: 45000, capacity: 50000, unit: "units", status: "high" },
];

export const productionMetrics = [
  { name: "Mon", production: 420, target: 400 },
  { name: "Tue", production: 390, target: 400 },
  { name: "Wed", production: 450, target: 400 },
  { name: "Thu", production: 480, target: 400 },
  { name: "Fri", production: 440, target: 400 },
  { name: "Sat", production: 310, target: 300 },
  { name: "Sun", production: 180, target: 200 },
];

export const salesBreakdown = [
  { name: "Industrial", value: 38, color: "#22d3ee" },
  { name: "Commercial", value: 28, color: "#3b82f6" },
  { name: "Export", value: 22, color: "#10b981" },
  { name: "Domestic", value: 12, color: "#8b5cf6" },
];

export const recentTransactions = [
  {
    id: "TXN-001",
    type: "purchase",
    description: "Copper Wire (Grade A) - 500kg",
    amount: "₹2,45,000",
    status: "completed",
    date: "2026-05-14",
    vendor: "MetalCorp Ltd.",
  },
  {
    id: "TXN-002",
    type: "sales",
    description: "Industrial Motors x 48 units",
    amount: "₹8,64,000",
    status: "completed",
    date: "2026-05-13",
    vendor: "PowerTech Industries",
  },
  {
    id: "TXN-003",
    type: "purchase",
    description: "Steel Sheets 3mm - 2 tons",
    amount: "₹1,80,000",
    status: "pending",
    date: "2026-05-13",
    vendor: "SteelWorks Inc.",
  },
  {
    id: "TXN-004",
    type: "sales",
    description: "Custom Circuit Assembly x 200",
    amount: "₹3,20,000",
    status: "processing",
    date: "2026-05-12",
    vendor: "TechSystems Co.",
  },
  {
    id: "TXN-005",
    type: "purchase",
    description: "Aluminum Extrusions - 1.5 tons",
    amount: "₹1,12,500",
    status: "completed",
    date: "2026-05-12",
    vendor: "AlumaCraft Pvt.",
  },
  {
    id: "TXN-006",
    type: "sales",
    description: "Transformer Units x 12",
    amount: "₹5,40,000",
    status: "completed",
    date: "2026-05-11",
    vendor: "GridPower Solutions",
  },
];

export const activityTimeline = [
  {
    id: 1,
    action: "Purchase Order #PO-2847 approved",
    user: "Rajesh Kumar",
    time: "2 min ago",
    type: "purchase",
    icon: "CheckCircle",
  },
  {
    id: 2,
    action: "Stock alert: Copper Wire below threshold",
    user: "System",
    time: "18 min ago",
    type: "alert",
    icon: "AlertTriangle",
  },
  {
    id: 3,
    action: "Sales invoice #INV-4521 generated",
    user: "Priya Sharma",
    time: "45 min ago",
    type: "sales",
    icon: "FileText",
  },
  {
    id: 4,
    action: "Production batch #B-901 completed",
    user: "Factory Floor",
    time: "1h 12min ago",
    type: "production",
    icon: "Factory",
  },
  {
    id: 5,
    action: "New vendor TechSystems Co. onboarded",
    user: "Admin",
    time: "3h ago",
    type: "system",
    icon: "UserPlus",
  },
  {
    id: 6,
    action: "Monthly revenue report exported",
    user: "Finance Team",
    time: "5h ago",
    type: "report",
    icon: "Download",
  },
];

export const stockAlerts = [
  {
    id: 1,
    item: "Copper Wire (Grade A)",
    current: 4820,
    minimum: 6000,
    unit: "kg",
    severity: "critical",
    message: "20% below minimum threshold",
  },
  {
    id: 2,
    item: "Circuit Boards (Type B)",
    current: 1800,
    minimum: 2000,
    unit: "units",
    severity: "warning",
    message: "10% below minimum threshold",
  },
  {
    id: 3,
    item: "Solder Wire (60/40)",
    current: 120,
    minimum: 200,
    unit: "rolls",
    severity: "critical",
    message: "40% below minimum threshold",
  },
];

export const orderStats = {
  pending: 47,
  processing: 128,
  shipped: 203,
  delivered: 1469,
  total: 1847,
};
